# Generated by Django 3.2.12 on 2022-02-14 00:50

import common.utilitary
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import tagulous.models.fields
import tagulous.models.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='slug')),
                ('published', models.DateTimeField(help_text="Programmé la date et l'heure de la formation.", verbose_name='date et de publication')),
                ('name', models.CharField(help_text='Saisir le titre du livre (200 caractères maximum).', max_length=200, verbose_name='titre du livre')),
                ('price', models.PositiveIntegerField(default=5000, help_text='Indiquer le prix de cet article.', verbose_name='prix de cet article')),
                ('resume', models.TextField(blank=True, help_text='faire un petit résumé de ce document (maximum 500 caractère)', max_length=500, null=True, verbose_name='résumé du livre')),
                ('cover', models.ImageField(help_text='ajouter une image de couverture de ce livre.', upload_to=common.utilitary.upload_image_to, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='ajouter une image de couverture')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de vues')),
            ],
            options={
                'verbose_name_plural': 'livres',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tagulous_Course_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='slug')),
                ('published', models.DateTimeField(help_text="Programmé la date et l'heure de la formation.", verbose_name='date et de publication')),
                ('name', models.CharField(help_text='Saisir le titre de cette formation (80 caractères maximum).', max_length=80, verbose_name='titre de la formation')),
                ('subtitle', models.CharField(blank=True, help_text='Saisir le sous-titre de cette formation (200 caractères maximum).', max_length=200, null=True, verbose_name='sous-titre')),
                ('price', models.PositiveIntegerField(default=5000, help_text='Indiquer le côut de cette formation.', verbose_name='côut de la formation')),
                ('date_of_course', models.DateTimeField(help_text="Indiquer la date & l'heure de la formation", verbose_name='date & heure de la formation')),
                ('location_of_course', models.CharField(help_text='Définir le lieux de la formation (200 caractères maximum)', max_length=200, verbose_name='Lieux de formation')),
                ('resume', models.TextField(blank=True, help_text='faire un petit résumé de cette formation (300 caractères maximum)', max_length=300, null=True, verbose_name='résumé')),
                ('description', models.TextField(blank=True, help_text='décrire la formation, les rubriques et les objectifs.', null=True, verbose_name='description')),
                ('cover', models.ImageField(help_text="ajouter une image descriptive de l'article.", upload_to=common.utilitary.upload_image_to, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='ajouter une image')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de vues')),
                ('option', models.CharField(choices=[('En Ligne', 'En Ligne'), ('En Présentiel', 'En Présentiel')], default='En Présentiel', help_text='Option de la formation', max_length=13, verbose_name='Option de la formation')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=5, to='course.Tagulous_Course_tags', verbose_name='mots clés')),
            ],
            options={
                'verbose_name_plural': 'formations',
                'ordering': ['-published'],
                'get_latest_by': ['-published'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uuid'], name='course_book_uuid_545e46_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['uuid'], name='course_cour_uuid_9e18a1_idx'),
        ),
    ]
