# Generated by Django 3.2 on 2022-01-10 14:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('Publié', 'Publié'), ('En Attente', 'En Attente')], default='En Attente', help_text='status.', max_length=10, verbose_name='status')),
                ('published', models.DateTimeField(help_text="Programmé la date et l'heure de la formation.", verbose_name='date et de publication')),
                ('name', models.CharField(help_text='Saisir le titre du livre (200 caractères maximum).', max_length=200, verbose_name='titre du livre')),
                ('price', models.PositiveIntegerField(default=5000, help_text='Indiquer le prix de cet article.', validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(1000000)], verbose_name='prix de cet article')),
                ('resume', models.TextField(blank=True, help_text='faire un petit résumé de ce document (maximum 500 caractère)', max_length=500, null=True, verbose_name='résumé du livre')),
                ('cover', models.ImageField(blank=True, help_text='ajouter une image de couverture de ce livre.', null=True, upload_to='formation/', verbose_name='ajouter une image de couverture')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de vues')),
            ],
            options={
                'verbose_name_plural': 'livres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('Publié', 'Publié'), ('En Attente', 'En Attente')], default='En Attente', help_text='status.', max_length=10, verbose_name='status')),
                ('published', models.DateTimeField(help_text="Programmé la date et l'heure de la formation.", verbose_name='date et de publication')),
                ('name', models.CharField(help_text='Saisir le titre de cette formation (200 caractères maximum).', max_length=200, verbose_name='titre')),
                ('subtitle', models.CharField(blank=True, help_text='Saisir le sous-titre de cette formation (200 caractères maximum).', max_length=180, null=True, verbose_name='sous-titre')),
                ('price', models.PositiveIntegerField(default=5000, help_text='Indiquer le côut de cette formation.', validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(1000000)], verbose_name='côut de la formation')),
                ('date_of_course', models.DateTimeField(help_text="Indiquer la date & l'heure de la formation", verbose_name='date & heure de la formation')),
                ('location_of_course', models.CharField(help_text='Définir le lieux de la formation.', max_length=200, verbose_name='Lieux de formation')),
                ('resume', models.TextField(blank=True, help_text='faire un petit résumé de cette formation.', max_length=300, null=True, verbose_name='résumé')),
                ('description', models.TextField(blank=True, help_text='décrire la formation, les rubriques et les objectifs.', null=True, verbose_name='description')),
                ('cover', models.ImageField(blank=True, help_text="ajouter une image descriptive de l'article.", null=True, upload_to='formation/', verbose_name='ajouter une image')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de vues')),
                ('option', models.CharField(choices=[('En Ligne', 'En Ligne'), ('En Présentiel', 'En Présentiel')], default='En Présentiel', help_text='Option de la formation', max_length=13, verbose_name='Option de la formation')),
            ],
            options={
                'verbose_name_plural': 'formations',
                'ordering': ['-published'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['uuid'], name='course_cour_uuid_9e18a1_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uuid'], name='course_book_uuid_545e46_idx'),
        ),
    ]
