# Generated by Django 3.2 on 2022-01-03 00:49

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(help_text='Saisir le titre du livre (200 caractères maximum).', max_length=200, verbose_name='titre du livre')),
                ('price', models.PositiveIntegerField(default=5000, help_text='Indiquer le prix de cet article.', validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(1000000)], verbose_name='prix de cet article')),
                ('resume', models.TextField(blank=True, help_text='faire un petit résumé de ce document (maximum 500 caractère)', max_length=500, null=True, verbose_name='résumé du livre')),
                ('cover', models.ImageField(blank=True, help_text='ajouter une image de couverture de ce livre.', null=True, upload_to='formation/', verbose_name='ajouter une image de couverture')),
                ('status', models.CharField(choices=[('Publié', 'Publié'), ('En attente', 'En attente')], default='En attente', help_text='status de publication du livre.', max_length=10, verbose_name='status')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de vues')),
            ],
            options={
                'verbose_name_plural': 'livres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='date_of_course',
            field=models.DateTimeField(help_text="Indiquer la date & l'heure de la formation", verbose_name='date & heure de la formation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=5000, help_text='Indiquer le côut de cette formation.', validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(1000000)], verbose_name='côut de la formation'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['uuid'], name='course_livr_uuid_28a591_idx'),
        ),
    ]
