# Generated by Django 3.2 on 2022-01-10 15:58

import common.utilitary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='ajouter une image de couverture de ce livre.', null=True, upload_to=common.utilitary.img_url, verbose_name='ajouter une image de couverture'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, help_text="ajouter une image descriptive de l'article.", null=True, upload_to=common.utilitary.img_url, verbose_name='ajouter une image'),
        ),
    ]
