# Generated by Django 3.2.10 on 2022-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220110_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug'),
        ),
    ]
