# Generated by Django 3.2 on 2022-01-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220103_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='Book',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='course_livr_uuid_28a591_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uuid'], name='course_book_uuid_545e46_idx'),
        ),
    ]
