# Generated by Django 3.2 on 2022-02-11 15:47

import common.utilitary
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(choices=[('Motivation', 'Motivation'), ('Spiritualité', 'Spiritualité'), ('Business & Entrepreneuriat', 'Business & Entrepreneuriat')], default='Business & Entrepreneuriat', help_text="Définir le type de catégorie de l'article.", max_length=180, unique=True, verbose_name="type de catégorie d'article")),
                ('cover', models.ImageField(blank=True, help_text='ajouter une image descriptive de cette catégorie.', null=True, upload_to=common.utilitary.upload_image_to, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='ajouter une image')),
            ],
            options={
                'verbose_name_plural': 'catégories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', max_length=225, null=True, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('Publié', 'Publié'), ('En Attente', 'En Attente')], default='En Attente', help_text='status.', max_length=10, verbose_name='status')),
                ('published', models.DateTimeField(help_text="Programmé la date et l'heure de la formation.", verbose_name='date et de publication')),
                ('name', models.CharField(help_text="Définir le titre de l'article.", max_length=180, verbose_name="titre de l'article")),
                ('subtitle', models.CharField(blank=True, help_text="Définir un sous-titre de l'article.", max_length=225, null=True, verbose_name='sous-titre')),
                ('body', models.TextField(help_text="Éditer le contenu de l'article.", verbose_name="Contenu de l'article")),
                ('price', models.PositiveIntegerField(blank=True, default=0, help_text='Si cet article est payant, indiquer le prix.', verbose_name='prix de cet article')),
                ('cover', models.ImageField(blank=True, help_text="ajouter une image descriptive de l'article.", null=True, upload_to=common.utilitary.upload_image_to, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])], verbose_name='ajouter une image')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de lecture')),
                ('reading', models.CharField(choices=[('Gratuit', 'Gratuit'), ('Payant', 'Payant')], default='Gratuit', help_text="définir l'option de lecture de cet article.", max_length=10, verbose_name='Option de lecture')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ['-published'],
                'get_latest_by': ['-published'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['uuid'], name='blog_catego_uuid_ced970_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['uuid'], name='blog_post_uuid_a20c8f_idx'),
        ),
    ]
