# Generated by Django 3.2 on 2022-01-10 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(blank=True, choices=[('Motivation', 'Motivation'), ('Spiritualité', 'Spiritualité'), ('Business & Entrepreneuriat', 'Business & Entrepreneuriat')], default='Business & Entrepreneuriat', help_text="Définir le type de catégorie de l'article.", max_length=30, null=True, unique=True, verbose_name="type de catégorie d'article")),
            ],
            options={
                'verbose_name_plural': 'catégories',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug')),
                ('name', models.CharField(help_text="Définir le titre de l'article.", max_length=255, unique=True, verbose_name="titre de l'article")),
                ('subtitle', models.CharField(blank=True, help_text="Définir un sous-titre de l'article.", max_length=255, null=True, verbose_name='sous-titre')),
                ('body', models.TextField(help_text="Éditer le contenu de l'article.", verbose_name="Contenu de l'article")),
                ('cover', models.ImageField(blank=True, help_text="ajouter une image descriptive de l'article.", null=True, upload_to='post/', verbose_name='ajouter une image')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de vues')),
                ('status', models.CharField(choices=[('Publié', 'Publié'), ('Brouillon', 'Brouillon'), ('Relecture', 'Relecture')], default='Brouillon', help_text="définir le status de l'article.", max_length=10, verbose_name='status')),
                ('reading', models.CharField(choices=[('Gratuit', 'Gratuit'), ('Payant', 'Payant')], default='Gratuit', help_text="définir l'option de lecture de cet article.", max_length=10, verbose_name='Option de lecture')),
                ('published', models.DateTimeField(help_text="Programmé la date et l'heure de publication", verbose_name='date et de publication')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='catégorie')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='mots clés')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ['-published'],
                'get_latest_by': ['-published'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['uuid'], name='blog_catego_uuid_ced970_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['uuid'], name='blog_post_uuid_a20c8f_idx'),
        ),
    ]
