# Generated by Django 3.2 on 2022-01-10 15:58

import common.utilitary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text="ajouter une image descriptive de l'article.", null=True, upload_to=common.utilitary.img_url, verbose_name='ajouter une image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(help_text="Programmé la date et l'heure de la formation.", verbose_name='date et de publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Publié', 'Publié'), ('En Attente', 'En Attente')], default='En Attente', help_text='status.', max_length=10, verbose_name='status'),
        ),
    ]
