# Generated by Django 3.2 on 2022-01-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name_plural': 'catégories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='published',
        ),
    ]
