# Generated by Django 3.2 on 2022-01-10 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220110_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Si cet article est payant, indiquer le prix.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='prix de cet article'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='nombre de lecture'),
        ),
    ]
