# Generated by Django 3.2.10 on 2022-01-12 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220110_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text="Définir le titre de l'article.", max_length=180, unique=True, verbose_name="titre de l'article"),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Si cet article est payant, indiquer le prix.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='prix de cet article'),
        ),
    ]
