# Generated by Django 3.2.10 on 2022-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220112_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text="Définir le titre de l'article.", max_length=255, unique=True, verbose_name="titre de l'article"),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug'),
        ),
    ]
