# Generated by Django 3.2.10 on 2022-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220112_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text="Définir le titre de l'article.", max_length=225, unique=True, verbose_name="titre de l'article"),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Automatiquement formé à partir du nom.', null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Définir un sous-titre de l'article.", max_length=225, null=True, verbose_name='sous-titre'),
        ),
    ]
