# Generated by Django 3.2.10 on 2022-01-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220112_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Si cet article est payant, indiquer le prix.', verbose_name='prix de cet article'),
        ),
    ]
