# Generated by Django 3.2.10 on 2022-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220112_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text="Définir le titre de l'article.", max_length=225, verbose_name="titre de l'article"),
        ),
    ]
