# Generated by Django 3.2.12 on 2022-02-23 17:36

import checkout.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0011_remove_course_location_of_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, verbose_name='adresse email')),
                ('first_name', models.CharField(max_length=80, verbose_name='nom')),
                ('last_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone')),
                ('phone_two', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone 2 (facultatif)')),
                ('city', models.CharField(default='Bouaké', max_length=80, verbose_name='ville')),
                ('country', models.CharField(blank=True, default="Côte d'Ivoire", max_length=80, null=True, verbose_name='pays')),
                ('address', models.CharField(max_length=180, verbose_name='adresse de livraison')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse ip')),
                ('id_checkout', models.CharField(default=checkout.models.random_checkout_code, editable=False, max_length=8, unique=True, verbose_name='ID Inscription')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.course', verbose_name='course')),
            ],
            options={
                'verbose_name_plural': 'inscrptions',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, verbose_name='adresse email')),
                ('first_name', models.CharField(max_length=80, verbose_name='nom')),
                ('last_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone')),
                ('phone_two', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone 2 (facultatif)')),
                ('city', models.CharField(default='Bouaké', max_length=80, verbose_name='ville')),
                ('country', models.CharField(blank=True, default="Côte d'Ivoire", max_length=80, null=True, verbose_name='pays')),
                ('address', models.CharField(max_length=180, verbose_name='adresse de livraison')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse ip')),
                ('id_checkout', models.CharField(default=checkout.models.random_checkout_code, editable=False, max_length=8, unique=True, verbose_name='ID Commande')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='course.book', verbose_name='livre')),
            ],
            options={
                'verbose_name_plural': 'commande de livre',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='registercourse',
            index=models.Index(fields=['uuid'], name='checkout_re_uuid_87eba2_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['uuid'], name='checkout_ch_uuid_232e1e_idx'),
        ),
    ]
