# Generated by Django 3.2 on 2022-01-10 17:25

import checkout.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_auto_20220110_1558'),
        ('blog', '0003_auto_20220110_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, verbose_name='adresse de messagerie')),
                ('first_name', models.CharField(max_length=80, verbose_name='nom')),
                ('last_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_two', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(max_length=80, verbose_name='ville')),
                ('country', models.CharField(max_length=80, verbose_name='pays')),
                ('address', models.CharField(blank=True, max_length=180, null=True, verbose_name='adresse de livraison')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('id_checkout', models.CharField(default=checkout.models.increment_order_number, editable=False, max_length=500, unique=True, verbose_name='ID Paiement')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_book', to='course.book', verbose_name='livre')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_post', to='blog.post', verbose_name='article')),
            ],
            options={
                'verbose_name_plural': 'commande',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['uuid'], name='checkout_ch_uuid_232e1e_idx'),
        ),
    ]
