# Generated by Django 3.2 on 2022-01-12 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(default=1, max_length=180, verbose_name='adresse de livraison'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(default='Bouaké', max_length=80, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(blank=True, default="Côte d'Ivoire", max_length=80, null=True, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone_two',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Le numéro de téléphone doit être saisi dans le format                '+225'. Jusqu'à 10 chiffres sont autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone 2 (facultatif)'),
        ),
    ]
